### ISSUE TITLE
'Tracer' object has no attribute '_noop_scope'

### ISSUE THREAD

**Issue by cliveseldon** [opentracing-contrib/python-flask#29]
Following the standard example but calling Flask.run explicitly, like:

```
       def initialize_tracer():
            from jaeger_client import Config
            config = Config(
                config={
                    'sampler': {'type': 'const', 'param': 1}
                },
                service_name='hello-world')
            return config.initialize_tracer() # also sets opentracing.tracer                                      

        def rest_prediction_server():
            app = seldon_microservice.get_rest_microservice(
                user_object, debug=DEBUG)


            from flask_opentracing import FlaskTracer

            flask_tracer = FlaskTracer(initialize_tracer, True, app)

            app.run(host='0.0.0.0', port=port)

```
I get on REST call:

```
Traceback (most recent call last):
  File "/home/clive/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/clive/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/clive/anaconda3/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/clive/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/clive/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/clive/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1811, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/clive/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2087, in preprocess_request
    rv = func()
  File "/home/clive/anaconda3/lib/python3.6/site-packages/flask_opentracing/tracing.py", line 39, in start_trace
    self._before_request_fn(traced_attributes)
  File "/home/clive/anaconda3/lib/python3.6/site-packages/flask_opentracing/tracing.py", line 121, in _before_request_fn
    child_of=span_ctx)
  File "/home/clive/anaconda3/lib/python3.6/site-packages/opentracing/tracer.py", line 126, in start_active_span
    return self._noop_scope
AttributeError: 'Tracer' object has no attribute '_noop_scope'

```

Any ideas?

**Comment by Jamim** [comment]
Hi @cliveseldon,

I believe that you missed one of two possible warnings when installed `Flask-OpenTracing` and `jaeger-client`:
```
flask-opentracing 1.0.0 has requirement opentracing<2.1,>=2.0, but you'll have opentracing 1.3.0 which is incompatible.
```
```
jaeger-client 3.13.0 has requirement opentracing<2,>=1.2.2, but you'll have opentracing 2.0.0 which is incompatible.
```

The root cause of the issue is that `Flask-OpenTracing==1.0.0` is not compatible with the latest `jaeger-client` since `jaeger-client` does not support `opentracing>=2` yet (see jaegertracing/jaeger-client-python#199).

To avoid this issue you can use `Flask-OpenTracing==0.2.0`.

**Comment by cliveseldon** [comment]
Thanks @Jamim  that indeed fixes things.
